version: '3.8'
services:
  api:
    container_name: api
    image: acrfilm.azurecr.io/event_api
    platform: linux/amd64
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "80:80"
